name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e82e7772190cbdb2404e13b1822f726c1abfa1d4284797420b6dc69f35360ddf"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
