name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c1bb48cf23b51bb3eeee5d9125e38760a5faa872ec4484231b6601e026511e9"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
