name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32a70505714f028fb7493f37b81fb207daadd32baa7151678e496ece73a76ef"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
