name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12b00aafa2949068f087ec0b865a984579af16cbf726aefc19345d44ca54680"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
