name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e27fc2f05e759f6165ecbcb6b77c84a520ee2690ae9ad2d4bdf460e13a9c81a7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
