name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbf9fbb0f68de176edce5f2c4d742a859e37c996e64abaa86d9ec4003cf9042"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
