name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "348fc734c133b3486a8ef166ef68c039bf1439b3536ddabf42b197e4aabcfddd"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
