name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eec273e805dde13474802bed466cf656ce648e681a360086b7066c02f902a142"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
