name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be49a13e6d0939ffd3888908e4891ed27b64a5cb694b209b6de0af273278a0ed"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
