name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d5dee040ecc53325ac2ef3175ceafa772b50dcf99331e5131a0ef57e40ecc8"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
