name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3ea7ca86fb6dac403df78fb8f3bbe5da54da1efc0a820b8f422be41c6b2fd74"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
