name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1593dffa78dc00e69abb620c6f345cf7f32e8aecedc5088d7751464f669dd16f"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
