name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69929e74e8c1a39b055ce91f0ea574efcf10dc002a056048f312be2adee71525"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
