name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e49a03033b5df160ac6767d6cfe90b408a2629336b3526f4add9729fa397e098"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
