name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d9ba53b6332a4bc8c72239116d0a69d430dcbc41c93770f365ee840c4d85fcd"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
