name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6aff0d3d38255073ddaa79d22d18355bdd067a5dea9497a768fedf2f4e49101"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
