name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a9a8f7283fc33f87b3840badcd4c86d3310d1ed4762aabbebe2625200a93acb"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
