name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47e9c6f8014ee94c238b0b7ba9fda7e25c46202def6ab570cbee65a47b2c15a7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
