["YetAnotherWorldProtector region configuration"]
	#Default region priority increment/decrement.
	#Range: 1 ~ 1000
	default_region_priority_inc = 5
	#Amount of pagination entries for CLI output of flags, region, children region, players, teams, etc.
	#Range: 5 ~ 15
	cli_entries_per_page = 10
	#Enable new dimensional regions on creation.
	dim_enable_new = true
	#Default flags for new local regions.
	# Make sure to put the flags in parentheses, just like a normal string.
	# Example: default_flags = ["no-pvp", "no-flight"])
	default_flags = ["break-blocks", "place-blocks", "scoop-fluids", "place-fluids", "ignite-explosives", "tools-secondary", "trample-farmland", "lightning", "fire-tick", "animal-taming", "spawning-monster", "use-items", "use-bonemeal", "no-pvp", "knockback-players", "melee-animals", "melee-villagers", "melee-wtrader", "explosions-blocks", "explosions-entities", "creeper-explosion-blocks", "creeper-explosion-entities", "zombie-destruction", "mob-griefing"]
	#Default flags for new dimensional regions.
	# Make sure to put the flags in parentheses, just like a normal string.
	# Example: dim_default_flags = ["invincible", "sleep", "spawning-all"])
	dim_default_flags = []
	#Default region priority for newly created regions.
	#Range: > 0
	default_region_priority = 10
