name = "ProjectCreate"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd04ca2dc67b4548eb0d0eb4ee78a700cbcb2c591312ac82dcf72adacc910f6a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
